### ISSUE TITLE
Add Ising model simulation to 'examples' section

### ISSUE THREAD

**Issue by rileyjshaw** [rileyjshaw/terra#21]
@crawfy48 made an Ising model simulation of 2D ferromagnetic material [here](https://github.com/crawfy48/Ising-model). IT'S AWESOME!

**Comment by rileyjshaw** [comment]
(Finally) done!

**Comment by crawfy48** [comment]
That's great! Just in time I've updated my model so now it has periodic boundary conditions, von Neumann neighborhood and more new features. Many thanks for making all those useful changes in Terra, now the model feels truly complete :)

**Comment by rileyjshaw** [comment]
@crawfy48 it looks great!! Glad you like the additions, they were good suggestions :+1:
