### ISSUE TITLE
Debug information while making stuff in terra

### ISSUE THREAD

**Issue by RossKinsella** [rileyjshaw/terra#26]
Hi !
# Background

I was going through your introduction over at http://rileyjshaw.com/terra and I got stumped by the following not working as demonstrated:

![screen shot 2015-03-13 at 13 11 14](https://cloud.githubusercontent.com/assets/6261577/6638916/810b19c8-c982-11e4-8eee-a12b8fd82da1.png)

Initially I thought the frequency of frames was too high so I set about counting the number of Ticks:
![screen shot 2015-03-13 at 13 13 58](https://cloud.githubusercontent.com/assets/6261577/6638948/dc44fcbe-c982-11e4-8bba-287923308b93.png)

It turned out only 8 ticks were happening.
-- At this point I realised the creature 'Plant' from the first screenshot was not initialised.
# So, my suggestion is:

Lets have some debug info available in terra from dev tools!

 One I have added in for myself is 'registeredCreatures':
![screen shot 2015-03-13 at 13 20 18](https://cloud.githubusercontent.com/assets/6261577/6639030/c2f9bb18-c983-11e4-884e-d9f98c959097.png)
# Note

I'm a noob, please excuse me if I missed an existing way of getting this information.

**Comment by RossKinsella** [comment]
Having gone through the rest of the tutorial over at http://rileyjshaw.com/terra, it might just be sufficient to give users something to copy-paste for simplePlant.

**Comment by rileyjshaw** [comment]
@RossKinsella thank you _SO_ much for the detailed report! This was a huge oversight on my part; I didn't realize that I'd skipped the `simplePlant` initialization in the tutorial. I just updated the site, let me know what you think!

**Comment by RossKinsella** [comment]
Looks good!
