### ISSUE TITLE
Use without node?

### ISSUE THREAD

**Issue by DaveEveritt** [rileyjshaw/terra#31]
Dumb beginner Q: is it possible to "play with" Terra in a static HTML page by just importing "https://cdn.jsdelivr.net/terra/latest/mainfile" i.e. no node, no Bower, no Gulp? Following [the guide](http://rileyjshaw.com/terra/#main) I'm getting: `Uncaught TypeError: Cannot read property 'appendChild' of null`.

**Comment by rileyjshaw** [comment]
@DaveEveritt that's strange! What happens if you put `console.log(document.body)` in the JS console?

The library should work on a static HTML page without any of the tools you mentioned.

**Comment by DaveEveritt** [comment]
Tried again, imported from the CDN, followed the code:

```javascript
// create a simple plant creature
terra.registerCreature({
  type: 'simplePlant',
  color: [166, 226, 46],
  size: 10,
  reproduceLv: 0.8,
  wait: function() { this.energy += 3; },
  move: false
});

// initialize our environment
var ex1 = new terra.Terrarium(25, 25, {id: 'ex1'});
ex1.grid = ex1.makeGridWithDistribution([['secondCreature', 10], ['simplePlant', 90]]);

ex1.animate(300);
```

but (with the error) `console.log(document.body)` only shows the body tag, no canvas element. Full error:

```javascript
Uncaught TypeError: Cannot read property 'appendChild' of null
    at Object.n [as createCanvasElement] (mainfile:1)
    at new n (mainfile:1)
    at index.html:23
```

line 23 is `var ex1 = new terra.Terrarium(25, 25, {id: 'ex1'});`.

**Comment by DaveEveritt** [comment]
Wait. My _stupid_. Bring in the terra script at the end of the `body` tag. Then the example. Working!!
